language: perl
before_install:
  - git clone --depth 1 https://github.com/sstephenson/bats.git
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install shellcheck;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-backports restricted main universe";
      sudo apt-get -y update;
      sudo apt-get -y install shellcheck;
    fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib);
      cpanm --quiet --notest Test::Perl::Critic Perl::Critic::Freenode
    fi
script:
  - ./bats/bin/bats test/*.bats
  - shellcheck diff-so-fancy update-deps.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      perlcritic -1 -q --theme freenode lib/diff-so-fancy.pl;
    fi
os:
  - linux
  - osx
