language: bash
before_install:
  - git clone --depth 1 https://github.com/sstephenson/bats.git
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install gnu-sed;
      brew install shellcheck;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-backports restricted main universe";
      sudo apt-get -y update;
      sudo apt-get -y install shellcheck;
    fi
script:
  - ./bats/bin/bats test/*.bats
  - shellcheck diff-so-fancy update-deps.sh
os:
  - linux
  - osx
